### ISSUE TITLE
How to relate functions and relations

### ISSUE THREAD

**Issue by lucasmoschen** [emap-md/book#42]
Guys, no one is responsible for relations' chapter nowadays. What do you think, I need opinions, about this: Do you think in the functions' chapter I start relating functions with relations, cause function would be a kind of relation or do you think I should put this relation after everything, the last, how it's in the logic and proof? Advice!!

Pessoal, ninguém é responsável pelo capítulo das relações hoje em dia. O que você acha, eu preciso de opiniões, sobre isso: você acha que no capítulo das funções eu começo a relacionar funções com relações, porque função seria um tipo de relação ou você acha que eu deveria colocar essa relação depois de tudo, o último, como está no livro Logig and Proof? Conselho!!

**Comment by lucasresck** [comment]
It seems to be more intuitive to me to leave this relation between functions and relations to the end. I think it creates an ideia that both are two distinct well described things, but they relate to the other somehow.

**Comment by alessandracid** [comment]
I agree with Lucas Emanuel

**Comment by yfaria** [comment]
Acho que concordo com o Emanuel.
Afinal de contas, não temos seguido ,aparentemente, um formalismo que um tratamento em teoria dos conjuntos normalmente exigiria. Mas é importante falar em algum momento do capítulo porque é importante né; é uma abstração desse formalismo que nos permite ver pela intuição como o instrumento de entrada e saída
