### ISSUE TITLE
Second and Higher-Order Logic

### ISSUE THREAD

**Issue by lucasmoschen** [emap-md/book#76]
This topic was introduced in the Functions' chapter. I understand why the author did that, but, why don't we insert this in the introduction? 

Este tópico foi introduzido no capítulo de Funções. Eu entendo o porquê o autor fez isso, mas, por que não inserimos esta parte na introdução?

**Comment by yfaria** [comment]
Acho meio complicado isso, mas concordo que pode ser dito antes.
A introdução (não tenho certeza se você está se referindo à introdução do livro, o capitulo) parte do pressuposto que o leitor não entende o que é LP nem FOL, tratar HOL seria meio complicado (mas dá pra passar por cima com uma visão geral por todos).
Eu acho que HOL podia ser comentado no final do capítulo de FOL, com uma breve explicação de algumas limitações expressivas desta linguagem (como impossibilidade de quantificar sobre predicados, relações e funções) e alguns comentários sobre aquela.

**Comment by lucasmoschen** [comment]
Certo então! Acho possível, então!

**Comment by lucasmoschen** [comment]
Estou incluindo no meu capítulo!
